---
env:
  es2022: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
parserOptions:
  project: ./tsconfig.json
rules: {}
