---
env:
  es2020: true
  node: true
extends:
  - airbnb
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parserOptions:
  project: ./tsconfig.json
rules:
  {}
