---
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - module-data:/usr/src/app/node_modules
    environment:
      DEBUG: nightmare*,electron:*

volumes:
  module-data:
    driver: local
