---
version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app:cached
      - module-data:/usr/src/app/node_modules:delegated
    environment:
      DEBUG: nightmare*,electron:*

volumes:
  module-data:
    driver: local
