---
name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.9.0
          cache: yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn build
